debugging syntax

diff --git a/pipeline/deployspec.yml b/pipeline/deployspec.yml
--- a/pipeline/deployspec.yml
+++ b/pipeline/deployspec.yml
@@ -56,13 +56,16 @@ phases:
       - terraform init -no-color
       - ami=$(terraform output instance_ami | grep ami | head -1 | tr -d ", \"")
       - echo "AMI [${ami}]"
-      - 'if [ -z "${ami}" ]; then echo "ERROR: cannot determine instance AMI" ; exit 1 ; fi'
+      - |
+        if [ -z "${ami}" ]; then
+          echo "ERROR: cannot determine instance AMI" ;
+          exit 1 ;
+        fi
       - terraform apply -auto-approve -no-color -var instance_ami="${ami}" --target=local_file.inventory --target=local_file.tfvars
       - cd ansible
       - ansible-playbook ${ansible_debug} deploy_backend_1.yml
       - source /tmp/env
-      - echo THEME_ONLY = $THEME_ONLY
-      # - >
+      # - |
       #   if [ "$THEME_ONLY" = "true" ]; then
       #     echo "DEBUG: Running limited theme update..."
       #   else
